name: Android CI

on:
  push:
    branches:
      - develop
      - feature/workflows
      - main
  pull_request:
    branches:
      - develop
      - feature/workflows
      - main

jobs:
  install_dependencies:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies (Gradle)
        run: ./gradlew dependencies

  lint:
    runs-on: windows-latest
    needs: install_dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run Lint Check
        run: ./gradlew lint

  run_tests:
    runs-on: windows-latest
    needs: install_dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies (Gradle)
        run: ./gradlew dependencies

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Run UI Tests
        run: ./gradlew connectedDebugAndroidTest

  build_apk:
    runs-on: windows-latest
    needs: [install_dependencies, lint, run_tests]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies (Gradle)
        run: ./gradlew dependencies

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: build-apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
